<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_iLfzibSQ</name>
   <tag></tag>
   <elementGuidId>dd048393-eccd-481e-aefa-1fb8635fedba</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mail']/div/span/b[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;mail&quot;)/div[1]/span[1]/b[2][count(. | //b[@ref_element = 'Object Repository/Page_Inbox/iframe_Undo_ifmail']) = count(//b[@ref_element = 'Object Repository/Page_Inbox/iframe_Undo_ifmail'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>b:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>8ed4cbd0-d4bc-4c6b-a3ba-0a6a0cc11f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ai6OoatK</value>
      <webElementGuid>fb7375eb-7e0e-48d3-9e59-748dfd0cf8a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mail&quot;)/div[1]/span[1]/b[2]</value>
      <webElementGuid>08c1df05-6509-480e-811d-03388edeb462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Inbox/iframe_Undo_ifmail</value>
      <webElementGuid>d60225ea-09a1-4741-834c-0410b9d14005</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mail']/div/span/b[2]</value>
      <webElementGuid>0c2f157a-3f67-4000-978e-d5e31a0df653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='invi'])[1]/following::b[1]</value>
      <webElementGuid>a6c51951-51b2-499e-98b0-143c378129b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::b[2]</value>
      <webElementGuid>f6397e5a-a462-4dd8-80d3-013ee2ef601b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'mail', '&quot;', ')/div[1]/span[1]/b[2]')])[1]/preceding::b[1]</value>
      <webElementGuid>82866f6e-8e3c-4db5-a86c-c17b59dbbe01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ai6OoatK']/parent::*</value>
      <webElementGuid>4cbdca62-48e7-423f-9e2f-c93c38eaa8bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b[2]</value>
      <webElementGuid>6033eff1-33bf-4ebb-8f11-0087c427cffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'Ai6OoatK' or . = 'Ai6OoatK')]</value>
      <webElementGuid>58334c5f-97cf-4148-95d3-7789063e67f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
