<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Individual</name>
   <tag></tag>
   <elementGuidId>952d5709-9408-47e4-bd88-3331e544ac39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/section/main/div/div/div/div[2]/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5df80c17-fdcb-4b70-9aa3-84135e059208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-account_selectBtn__axtHp</value>
      <webElementGuid>37d717be-3892-4005-8252-478fc12d211c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Individual</value>
      <webElementGuid>d0b4c722-1177-41aa-a24c-4adca723c22a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/section[@class=&quot;ant-layout bare_antLayoutBare__J0oRq bare_antLayoutBareWithBackgroundImg__EqjMI&quot;]/main[@class=&quot;ant-layout-content bare_antLayoutContentBare__4J3jv&quot;]/div[@class=&quot;ant-row ant-row-center&quot;]/div[@class=&quot;ant-col ant-col-8 select-account_selectAccount__-e-J+&quot;]/div[@class=&quot;ant-space ant-space-vertical&quot;]/div[@class=&quot;ant-space-item&quot;]/div[@class=&quot;ant-row&quot;]/div[@class=&quot;ant-col select-account_WrapButtonMobile__6gtzP ant-col-xs-24 ant-col-sm-24 ant-col-md-12 ant-col-lg-12&quot;]/div[@class=&quot;select-account_selectBtn__axtHp&quot;]</value>
      <webElementGuid>50f15c03-9b22-4426-81e3-b168c7943c57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section/main/div/div/div/div[2]/div/div[2]/div</value>
      <webElementGuid>db1ef9b5-abd0-489a-89d4-1a50cc58be6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Corporate'])[1]/following::div[2]</value>
      <webElementGuid>c97c59c5-ff87-4295-9897-0280fb897ddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select User Type'])[1]/following::div[9]</value>
      <webElementGuid>3fbd8578-a1be-4d0e-b375-04a2015d3647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Already Registered?'])[1]/preceding::div[3]</value>
      <webElementGuid>699affe0-052f-4bc0-b7c5-e2842f5fbfb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div</value>
      <webElementGuid>341731c4-0efe-4c34-95e8-98eb5d0ce184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Individual' or . = 'Individual')]</value>
      <webElementGuid>72c4b0d3-dfd0-43ef-a508-fdd729d84719</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
