<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Logout_inMenu</name>
   <tag></tag>
   <elementGuidId>ae1a58e7-ede8-4fbb-b510-10022db445a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.menu_logoutIcon__Y3Xhe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/section/main/div[2]/div/div/div[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>834f3096-8ff9-496c-8d23-e1a5090d5fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu_logoutIcon__Y3Xhe</value>
      <webElementGuid>612ce412-578e-4575-bcbb-c995cef6b49a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>5bb2e558-458e-44e3-ba96-df49e00eb3f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/section[@class=&quot;ant-layout&quot;]/main[@class=&quot;ant-layout-content main_mainLayoutContent__Enlzb&quot;]/div[@class=&quot;ant-row&quot;]/div[@class=&quot;ant-col ant-col-xs-0 ant-col-sm-0 ant-col-md-0 ant-col-lg-6&quot;]/div[@class=&quot;menu_menuContainer__FdmxH&quot;]/div[@class=&quot;menu_logoutIcon__Y3Xhe&quot;]</value>
      <webElementGuid>2c522cfc-4f11-4cdd-8038-77611b659d50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section/main/div[2]/div/div/div[5]</value>
      <webElementGuid>c8fe46ee-dd04-447e-adda-4dd44ebd9e5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Request'])[1]/following::div[1]</value>
      <webElementGuid>81cf8bfd-6f53-4063-91bd-4e9396a9e9a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account'])[1]/following::div[4]</value>
      <webElementGuid>45212f7f-0950-4143-9487-e31c42c6b42e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Become a Funder or Borrower.'])[1]/preceding::div[2]</value>
      <webElementGuid>44f06530-eeea-4f61-a912-c3bb3d5cf115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]</value>
      <webElementGuid>4570f54e-8d90-4840-a970-b89fc8815fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>046707ab-5ce9-431c-9065-c6c5011bda35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
