<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OTPmail</name>
   <tag></tag>
   <elementGuidId>fe459d74-2386-4e8e-a63b-0d31c236f31e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div[2]/div[2]/div[2]/div/div/div/div[3]/div/div[3]/div[1]/div[2]/div/div/div/div/div/div[1]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.XG5Jd.JtO0E</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d6b31db4-263e-4248-ab86-5290577e4a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>XG5Jd JtO0E</value>
      <webElementGuid>9f0a82b5-fc05-476c-8aec-9107252d2578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PLPropCap Technologies LimitedPropCap - Validate OTP4:48 PMDear Minh.Nguyen2, You are trying to log in PropCap portal using your email address and password. As a security measure, you are requested to enter the OTP code (one-time-password) provided in email. The OTP code is: RiuUBAaY Thank you. PropCa</value>
      <webElementGuid>90b6a81c-683e-4732-8c0c-b1ecb54f891d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AQAAAUfMoqgBAAACTNlupgAAAAA=&quot;)/div[1]/div[@class=&quot;zKDWD YbB6r IKvQi IjQyD JCRRb G1NES&quot;]/div[@class=&quot;XG5Jd JtO0E&quot;]</value>
      <webElementGuid>15686c83-ec8f-46c3-8bd6-4f172d0bcce0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AQAAAUfMoqgBAAACTNlupgAAAAA=']/div/div/div[1]</value>
      <webElementGuid>b921995f-32cf-40dd-88dd-60936b4851b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>951b259e-b3d9-49e9-a0f5-6e433ec5f9cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'PLPropCap Technologies LimitedPropCap - Validate OTP4:48 PMDear Minh.Nguyen2, You are trying to log in PropCap portal using your email address and password. As a security measure, you are requested to enter the OTP code (one-time-password) provided in email. The OTP code is: RiuUBAaY Thank you. PropCa' or . = 'PLPropCap Technologies LimitedPropCap - Validate OTP4:48 PMDear Minh.Nguyen2, You are trying to log in PropCap portal using your email address and password. As a security measure, you are requested to enter the OTP code (one-time-password) provided in email. The OTP code is: RiuUBAaY Thank you. PropCa')]</value>
      <webElementGuid>770055bd-6be0-49f3-acae-d2dc591d98d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
